### PR TITLE
Qna081421

### PR DESCRIPTION
**Pull request by a-nouraldean**
@EJLEE808 @Taniel-P @PBandJaimie 
It is not as bad as it looks. I had to delete all node modules and coverage files as I accidently untracked them at some point.

- All planned components rendering
- Added Enzyme functionality for user tests

### CODE REVIEW

**Review by EJLEE808 — COMMENTED** [review]
Nice tests for Jest. Lots of data here.

I see the time of day click logs, I think. 
I should ask about that.

**Review by EJLEE808 — COMMENTED** [review]
Whoa line 6 of server/routes, that's pretty cool.

**Review by EJLEE808 — COMMENTED** [review]
Whoa line 6 of server/routes, that's pretty cool.

Nice try catch w/ async await.

**Review by EJLEE808 — COMMENTED** [review]
CSS in a different file. ok ok I like it.

**Review by EJLEE808 — COMMENTED** [review]
Pretty clean here.

**Comment by a-nouraldean** [comment]
@EJLEE808 I wish I could take credit for it but it is just the express doc instructions for async await

http://expressjs.com/en/advanced/best-practice-performance.html#use-try-catch

**Review by EJLEE808 — COMMENTED** [review]
Don't really know what to say here.
Looks pretty standard

**Review by EJLEE808 — COMMENTED** [review]
Looks pretty standard.

I don't think you needed the console.log(this.props.qAndA.data)
I think you could've just said {this.props.qAndA.data}

**Review by EJLEE808 — COMMENTED** [review]
Looks pretty standard.

I don't think you needed the console.log(this.props.qAndA.data)
I think you could've just said {this.props.qAndA.data}

I'll still approve it, but change for next time

**Review by EJLEE808 — COMMENTED** [review]
Nice, went from stubs to refactor'd component

**Comment by a-nouraldean** [comment]
> Looks pretty standard.
> 
> I don't think you needed the console.log(this.props.qAndA.data)
> I think you could've just said {this.props.qAndA.data}
> 
> I'll still approve it, but change for next time

It is probably left it there from earlier bug. I will remove.

**Review by EJLEE808 — COMMENTED** [review]
That pesky reseeded data... Nice

**Review by EJLEE808 — COMMENTED** [review]
<title>Atelier</title> 
 I like it I like it.
 
 EVENTUALLY, we all need to change our CSS to not use px. But that's a problem for future cheddar members (myself super included b/c I have no css)
 styles.css line 10
 
 I think you got it on line 295 w/ 30em.
 
 I'll approve for this time, but fix later. 
 ReviewTiles.jsx
    let reviews;
    let displayedReviews;
    Can just be 
  let reviews, displayedReviews;
  Same for SingleTile.jsx lines 50-53.
  
  
  Fun to try at Sort.jsx
  Try a ternary operator at lines 26-30. Nothing major. 
  
  This is for me, what's useEffect for on ProductCard. I just want to learn more React ;)

**Comment by a-nouraldean** [comment]
> <title>Atelier</title> I like it I like it.
> EVENTUALLY, we all need to change our CSS to not use px. But that's a problem for future cheddar members (myself super included b/c I have no css)
> styles.css line 10
> 
> I think you got it on line 295 w/ 30em.
> 
> I'll approve for this time, but fix later.
> ReviewTiles.jsx
> let reviews;
> let displayedReviews;
> Can just be
> let reviews, displayedReviews;
> Same for SingleTile.jsx lines 50-53.
> 
> Fun to try at Sort.jsx
> Try a ternary operator at lines 26-30. Nothing major.
> 
> This is for me, what's useEffect for on ProductCard. I just want to learn more React ;)

Is this for me or Jaimie?

**Pull request merged**
